name: CI Pipeline #label 

#runs on events
on:
  push:
    branchs: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Testing code
        uses: actions/checkout@v4 #downloading to vm
      
      - name: Install dependencies
        run: npm --prefix frontend ci
      
      - name: Run Tests
        run: echo "we did it"